import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Sidebar for the 'systematic-trading' docs folder
  systematicTradingSidebar: [{ type: 'autogenerated', dirName: 'systematic-trading' }],
};

export default sidebars;
